import { createElement, useState } from 'react'
import { ArrowUpRight, ArrowRight, Sun, Moon, Menu, X, MessageSquare, Phone, Calendar, Mail, RefreshCw, FileText, Sparkles, Check, Plus, Minus, Zap } from 'lucide-react'
import { ThemeProvider } from './context/ThemeContext'
import { useTheme } from './context/useTheme'
import PointerEffects, { ScrollEffects } from './components/ui/PointerEffects'
import Portfolio from './components/Portfolio'

const solutions = [
  ['Customer enquiries', 'A great first impression. Every time.', 'Respond to customers across your website, email and messaging channels.', MessageSquare, 'A customer asks about your services. Lumen answers using your business information and collects the details your team needs.'],
  ['AI phone assistants', 'Never miss the conversation.', 'Answer calls, qualify enquiries and help customers book appointments.', Phone, 'An incoming caller explains what they need. Your assistant collects their details and routes the enquiry to the right person.'],
  ['Bookings & appointments', 'Your calendar, taken care of.', 'Arrange appointments and send timely reminders automatically.', Calendar, 'Customers choose an available appointment. The booking is added to your calendar and a reminder is sent before their visit.'],
  ['Email automation', 'An inbox that moves itself.', 'Sort, understand and respond to repetitive emails.', Mail, 'Routine questions get an approved response, while sensitive or unusual requests are flagged for your team.'],
  ['Customer follow-ups', 'Keep opportunities moving.', 'Follow up with potential customers so opportunities don’t disappear.', RefreshCw, 'After a quote is sent, a timely follow-up checks whether the customer needs help and updates your records.'],
  ['Content & social media', 'More presence. Less preparation.', 'Turn your business knowledge into posts, captions and content.', Sparkles, 'Turn a service update into draft social posts, ready for your team to review and publish.'],
  ['Documents & admin', 'Give your team their time back.', 'Extract information and automate repetitive administrative work.', FileText, 'Details from a document are organised into your business systems, with exceptions sent to a person for review.'],
]
const industries = ['Property', 'Construction', 'Trades', 'Professional Services', 'Retail', 'Hospitality', 'Recruitment', 'Marketing', 'Other']
const examples = ['Qualify property enquiries and arrange viewings.', 'Collect project details and organise quote requests.', 'Handle job enquiries while your team is on site.', 'Route client enquiries and simplify appointment scheduling.', 'Answer product questions and organise customer requests.', 'Handle booking enquiries and common guest questions.', 'Collect candidate details and coordinate interviews.', 'Prepare content drafts and organise campaign enquiries.', 'If your business has repetitive work, there’s a good chance Lumen can help.']
const faqs = [ ['What does Lumen actually do?', 'Lumen designs and builds AI-powered systems that automate repetitive business processes. Each system is built around your business and the way your team works.'], ['Do I need to understand AI?', 'No. Tell us what you want to improve and we’ll identify where AI and automation could help.'], ['Can you work with our existing tools?', 'In many cases, yes. We can integrate AI systems with existing business tools and workflows where technically appropriate.'], ['Is Lumen suitable for a small business?', 'Yes. Solutions can be designed around the size and needs of your business.'], ['How much does it cost?', 'Every Lumen system is designed around the business and its requirements. Contact us to discuss your needs and receive a tailored proposal.'], ['How long does it take?', 'This depends on the complexity of the system. We’ll provide an estimated timeline after understanding your requirements.'] ]
function Logo({ large = false }) { const { theme } = useTheme(); return <span className={`${large ? 'hero-logo' : 'brand-logo'} logo-lockup`}><img src="/images/lumen-light-transparent.png" alt="Lumen" width="1254" height="1254"/>{theme === 'dark' && <img className="logo-white-wordmark" src="/images/lumen-light-transparent.png" alt="" aria-hidden="true" width="1254" height="1254"/>}</span> }

function Demo() {
 const [step, setStep] = useState(0); const [value, setValue] = useState(''); const [answers, setAnswers] = useState([])
 const prompts = ['Absolutely. We cover North London. I can collect a few details so the team can prepare your quote. What’s the property postcode?', 'Thank you. What type of renovation are you planning?', 'And what’s your preferred timeframe?']
 function reply(e) { e.preventDefault(); if (!value.trim()) return; setAnswers([...answers, value.trim()]); setValue(''); setStep(step + 1) }
 return <div className="demo-window"><div className="demo-bar"><span><i /> Lumen assistant</span><span>ILLUSTRATIVE DEMO</span></div><div className="conversation"><p className="bubble customer">Hi, I’m looking for a quote for a bathroom renovation. Do you cover North London?</p>{prompts.slice(0, Math.min(step + 1, 3)).map((p, i) => <div key={p}><p className="speaker">✦ LUMEN AI</p><p className="bubble">{p}</p>{answers[i] && <p className="bubble customer">{answers[i]}</p>}</div>)}{step === 3 && <div className="qualified"><Check size={19} /> Enquiry qualified <p>Your details are ready for the team. In a connected system, Lumen can update your records and trigger a follow-up.</p><button onClick={() => {setStep(0); setAnswers([])}}>Try again ↗</button></div>}</div>{step < 3 && <form className="chat-input" onSubmit={reply}><input aria-label={['Property postcode', 'Type of renovation', 'Preferred timeframe'][step]} placeholder={['Enter a postcode…', 'Tell us about the renovation…', 'When would you like to start?'][step]} value={value} onChange={e => setValue(e.target.value)} required maxLength={300} /><button aria-label="Send reply"><ArrowRight size={20} /></button></form>}<p className="demo-note">A guided example, not a live AI agent. Nothing here is submitted.</p></div>
}
function EnquiryForm({ demo = false }) {
 const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false)
 async function submit(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); data.improvements = new FormData(e.currentTarget).getAll('improvements'); data.type = demo ? 'demo' : 'enquiry'; const endpoint = import.meta.env.VITE_ENQUIRY_ENDPOINT; if (!endpoint) {setStatus('Online enquiries are not connected yet. Your details have not been sent. Please try again once the contact service is available.'); return} setBusy(true); try {const res = await fetch(endpoint, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data)}); if (!res.ok) throw new Error(); setStatus('Thank you. Your request has been sent. We’ll review your requirements and get back to you.'); e.target.reset()} catch {setStatus('We couldn’t send your request. Your details are still here so you can try again.')} finally {setBusy(false)} }
 return <form onSubmit={submit} className="enquiry-form"><div className="form-grid"><label>Name<input name="name" autoComplete="name" required placeholder="Your name" /></label><label>Business name<input name="business" autoComplete="organization" required placeholder="Your business" /></label><label>Email<input type="email" name="email" autoComplete="email" required placeholder="you@business.com" /></label>{!demo && <label>Website <span>(optional)</span><input type="url" name="website" placeholder="https://" /></label>}</div>{!demo && <><div className="form-grid"><label>Industry<select name="industry" required><option value="">Select your industry</option>{industries.map(i => <option key={i}>{i}</option>)}</select></label><label>People in your business<select name="size"><option>Just me</option><option>2–10</option><option>11–50</option><option>51–200</option><option>201+</option></select></label></div><label>What’s taking up too much of your team’s time?<textarea name="requirements" required placeholder="Tell us what’s slowing your business down…" rows={4} /></label><fieldset><legend>What would you like to improve?</legend><div className="checkboxes">{['Customer enquiries', 'Phone calls', 'Bookings', 'Emails', 'Admin', 'Follow-ups', 'Social media', 'Other'].map(s => <label key={s}><input type="checkbox" name="improvements" value={s} />{s}</label>)}</div></fieldset><label>Anything else we should know? <span>(optional)</span><textarea name="notes" rows={2} /></label></>}<button className="button primary" disabled={busy}>{busy ? 'Sending…' : demo ? 'Request a Demo' : 'Let’s Build Something'}<ArrowUpRight size={18}/></button><p className="small muted">We’ll review your requirements and get back to you with potential solutions.</p>{status && <p className="form-status" role="status">{status}</p>}</form>
}
function Website() {
 const { theme, toggleTheme } = useTheme(); const [menu, setMenu] = useState(false); const [selected, setSelected] = useState(null); const [industry, setIndustry] = useState(0); const [demoOpen, setDemoOpen] = useState(false)
 return <><PointerEffects/><ScrollEffects/><a className="skip-link" href="#main">Skip to content</a><header><a href="#" aria-label="Lumen home"><Logo /></a><nav className={menu ? 'open' : ''}>{[['Solutions','solutions'],['Our work','work'],['Industries','industries'],['About','about']].map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="icon-button" onClick={toggleTheme} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}>{theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>}</button><a href="#contact" className="button nav-cta">Let’s talk <ArrowUpRight size={16}/></a><button className="icon-button menu-button" aria-label="Toggle menu" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div></header>
 <main id="main"><section className="hero"><div className="hero-grid"/><div className="hero-inner"><div className="eyebrow"><i/> INTELLIGENT SYSTEMS. REAL-WORLD IMPACT.</div><div className="hero-layout"><div><h1>The future<br/><span className="outline">runs on</span> <em>Lumen.</em></h1><p className="hero-lead">AI systems that handle the work<br className="desktop-break"/> behind your business.</p><p className="hero-copy">From customer enquiries and appointments to follow-ups, administration and content — built around the way you work.</p><div className="hero-buttons"><a className="button primary" href="#contact">Build My AI System <ArrowUpRight size={19}/></a><a className="button secondary" href="#solutions">See What Lumen Can Do <ArrowRight size={18}/></a></div></div><div className="hero-art"><div className="orbit-label">BUILT AROUND YOU <span>✦</span> POWERED BY POSSIBILITY</div><Logo large/><div className="art-caption"><span className="status-dot"/> LESS REPETITION. MORE POSSIBILITY.</div></div></div><div className="hero-bottom"><span>Built for businesses. Designed around you.</span><a href="#solutions">SCROLL TO EXPLORE ↓</a><span>01 / A BRIGHTER WAY TO WORK</span></div></div></section>
 <div className="ticker"><span>YOUR BUSINESS, AMPLIFIED</span><b>✳</b><span>LESS BUSYWORK</span><b>✳</b><span>MORE POSSIBILITY</span><b>✳</b><span>BUILT AROUND YOU</span><b>✳</b></div>
 <section id="solutions" className="section"><div className="section-heading"><div><p className="eyebrow">01 / THE POSSIBILITIES</p><h2>What could you<br/><span className="muted">automate?</span></h2></div><p>You know your business.<br/>We know what technology can take off your plate.</p></div><div className="solutions-grid">{solutions.map(([title,tag,desc,Icon],i) => <button key={title} className={`solution-card card-${i}`} onClick={() => setSelected(selected === i ? null : i)} aria-expanded={selected === i}><div className="card-top"><span>0{i+1}</span>{createElement(Icon, { size: 25, strokeWidth: 1.4 })}</div><h3>{title}</h3><p>{desc}</p><div className="card-bottom"><span>{tag}</span>{selected === i ? <Minus size={18}/> : <ArrowUpRight size={18}/>}</div>{selected === i && <div className="solution-detail">{solutions[i][4]}</div>}</button>)}<a className="solution-card custom-card" href="#contact"><Sparkles size={28}/><h3>A different<br/>kind of challenge?</h3><p>Tell us what you’re trying to achieve.</p><div className="card-bottom">Let’s figure it out <ArrowUpRight size={23}/></div></a></div></section>
 <section className="problem section" id="about"><p className="eyebrow">02 / NO AI EXPERTISE REQUIRED</p><h2>You bring the problem.<br/><span className="muted">We build the solution.</span></h2><div className="problem-bottom"><figure><img className="brand-story-image" src="/images/connected-intelligence.png" alt="Blue glass connections join around a warm amber centre, an illustration of connected business workflows" loading="lazy" width="1536" height="1024"/><figcaption className="brand-image-caption">Connected workflows. One shared purpose.</figcaption></figure><div><p>You don’t need to know which AI tools to use, what automation to build or how to connect your systems.</p><p className="muted">Simply tell us what’s taking too much time, costing you money or creating unnecessary work. We’ll work out what can be automated.</p><a className="text-link" href="#contact">Tell Lumen Your Problem <ArrowUpRight size={20}/></a></div></div></section>
 <section className="section" id="process"><p className="eyebrow">03 / FROM PROBLEM TO POSSIBILITY</p><h2>Simple for you.<br/><span className="muted">Powerful for your business.</span></h2><div className="process-grid">{[['Tell us','Tell us what your business does and what’s slowing you down.'],['We design','We identify opportunities for automation and design a system around your workflow.'],['You move forward','We build, integrate and deploy your AI system. Your business keeps moving. Lumen handles the repetitive work.']].map(([t,d],i)=><article key={t}><span className="step-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section id="industries" className="section industry-section"><div className="section-heading"><div><p className="eyebrow">04 / YOUR WORLD. YOUR WORKFLOW.</p><h2>Built for the way<br/>your industry works.</h2></div><p>No one-size-fits-all systems.<br/>Just the right solution for your business.</p></div><div className="industry-buttons">{industries.map((v,i)=><button key={v} className={industry === i ? 'active' : ''} onClick={()=>setIndustry(i)} aria-pressed={industry === i}>{v}<ArrowUpRight size={16}/></button>)}</div><div className="industry-example" aria-live="polite"><span>{industries[industry]} / THE POSSIBILITIES</span><p>{examples[industry]}</p></div><p className="muted small">Don’t see your industry? If your business has repetitive work, there’s a good chance Lumen can help.</p></section>
 <section className="section"><p className="eyebrow">05 / A BETTER WAY TO WORK</p><h2>Less busywork.<br/><span className="muted">More business.</span></h2><div className="comparison"><article><div className="comparison-title">Without Lumen <span>THE MANUAL WAY</span></div>{['Customer enquiry arrives','An employee notices it','Someone finds time to reply','The customer waits','The follow-up gets forgotten','A potential customer disappears'].map((s,i)=><div className="flow-row" key={s}><span>{i===5?'×':'↓'}</span>{s}</div>)}</article><article className="with-lumen"><div className="comparison-title">With Lumen <span>THE CONNECTED WAY</span></div>{['Customer enquiry arrives','Lumen responds instantly','Qualifies the customer','Books an appointment','Updates your systems','Automatically follows up'].map(s=><div className="flow-row" key={s}><Check size={17}/>{s}</div>)}</article></div><p className="small muted">Illustrative workflow. Your system’s capabilities depend on the agreed scope and integrations.</p></section>
 <section id="demo" className="section demo-section"><div><p className="eyebrow">06 / SEE THE POSSIBILITIES</p><h2>Don’t just<br/>imagine it.<br/><span className="muted">Try it.</span></h2><p className="demo-copy">An enquiry comes in. Lumen helps move it forward. Explore a simple example of an assistant qualifying a renovation enquiry.</p><button className="text-link" onClick={()=>setDemoOpen(true)}>Request a personalised demo <ArrowUpRight size={19}/></button></div><Demo/></section>
 <Portfolio/><section className="belief section"><p className="eyebrow">THE LUMEN APPROACH</p><h2>Technology should work<br/>for people.</h2><p>We combine software engineering, automation and artificial intelligence to create systems designed around real-world workflows. We build AI when it solves a problem.</p><span>Practical systems. Human possibilities.</span></section>
 <section className="section faq-section"><div><p className="eyebrow">07 / A LITTLE MORE CLARITY</p><h2>Good questions.<br/><span className="muted">Clear answers.</span></h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
 <section className="section contact-section" id="contact"><div><p className="eyebrow">08 / YOUR NEXT CHAPTER</p><h2>Let’s find out<br/>what Lumen<br/>can automate<span className="accent">.</span></h2><p>You don’t need a technical brief.<br/>Just a problem worth solving.</p><div className="contact-note"><Zap size={22}/><span>Built for businesses.<br/>Designed around you.</span></div></div><EnquiryForm/></section>
 </main><footer><div className="footer-top"><div><Logo/><p>The Future Runs on Lumen.</p></div><div className="footer-links"><a href="#solutions">Solutions</a><a href="#industries">Industries</a><a href="#about">About</a><a href="#contact">Contact</a><button onClick={()=>setDemoOpen(true)}>Request a Demo ↗</button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Lumen</span><span>AI systems built around the way your business works.</span><a href="#">BACK TO TOP ↑</a></div></footer>
 {demoOpen && <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setDemoOpen(false)}}><dialog open aria-labelledby="demo-title" onKeyDown={e=>{if(e.key==='Escape')setDemoOpen(false)}}><button className="modal-close icon-button" autoFocus onClick={()=>setDemoOpen(false)} aria-label="Close demo request"><X/></button><p className="eyebrow">LET’S EXPLORE</p><h2 id="demo-title">See what’s possible.</h2><p>Tell us a little about your business to request a personalised demo.</p><EnquiryForm demo/></dialog></div>}
 </>
}
export default function App(){return <ThemeProvider><Website/></ThemeProvider>}
